### ISSUE TITLE
Is there any running website to try a live demo?

### ISSUE THREAD

**Issue by JeanCollas** [mobsoftware/mobsocial#17]
I am currently investigating social networks, I am considering a joomla based solution however I would prefer C#/ASP.Net.
I could consider using this solution and participating to the development (I would have many things to add! :) ), but first I would like to see how it looks like!

**Comment by mobsoftware** [comment]
Hi Jean, 

Sounds great! :) We are setting up a demo which will be announced soon. In the mean time, you can browse some of the current features [here](http://www.skatemob.com/Team/1). Feel free to add any features or suggestions to GitHub. And, if you aspire, a joomla plugin based on the [mobSocial] platform :) If you do decide to create a plugin, please let us know about it so you can offer it in the marketplace. 

Thanks,
Bruce

**Comment by JeanCollas** [comment]
Is there any way to contact you on skype/fb/other to discuss?

**Comment by mobsoftware** [comment]
Hey Jean, yes, you can contact me directly on Skype at bruce.leggett.1. Feel free to send me a message and we can schedule a time to chat. Thanks, Bruce

**Comment by eretontali** [comment]
Hi, is this a standalone application or just a NopCommerce plugin? I haven't been able to setup and run. Is there any documentation?. Thanks.  Edgar

**Comment by wittyansh** [comment]
Hi Edgar,
This is a standalone version. The nopCommerce plugin version has been moved to it's [new repo](https://github.com/mobsoftware/mobSocial.nopCommercePlugin)
The installation screen are yet to be created. You can however install the api by sending a post request to /api/install endpoint with parameters 

1. ConnectionString
2. AdminEmail
3. Password

You can use any http client search as Postman to perform this. Once you get success response, you can navigate to index page and see everything working :)

Do let me know if you face any issue.

**Comment by eretontali** [comment]
Sorry, I can´t, it throws an error when I try to run the API to install.
ArgumentException in 
"public DatabaseContext(string nameOrConnectionString) : base(nameOrConnectionString)"

Is the file "HttpContext.Current.Server.MapPath("~/App_Data/database.config")" missing ?

**Comment by wittyansh** [comment]
Hi Edgar, Can you please share the data that you are sending in post request (a screenshot if possible).
I can't reproduce the issue at my end.

**Comment by wittyansh** [comment]
Hi Edgar, you were right. There was an issue with the task manager that was causing the error you mentioned. I have just [fixed](https://github.com/mobsoftware/mobsocial/commit/02b8edb7f2eed2709cf4670adc6a8050235e4996) it. Can you give it a try and let me know if that solves the issue for you?

**Comment by eretontali** [comment]
Hi wittyansh, it works! database installed. Thank you!.
I have another issue. I can't see anything when I open index.html. 
I have Visual Studio 2015 and I'm setting the solution with 2 initial projects (Web Api and Web App). My browser is Google Chrome (and I tried Microsoft Edge too).
What am I missing?  (sorry for my bad english).  
![issue](https://cloud.githubusercontent.com/assets/7683891/19735364/e03151bc-9b70-11e6-9ee4-57d1466fa0cb.JPG)

**Comment by wittyansh** [comment]
Hi Edgar, can you please check if there are any errors being shown using F12-Developer tools. Please let me know if there are any.

**Comment by CS-begginer** [comment]
Hi @wittyansh 
How I can find Any get start Document for MobSocial?
I want Run MobSocial with VS 2015 :(

**Comment by wittyansh** [comment]
Hi @CS-begginer ,
We are still in the process of making documentation.
For now, let me list steps you'll need to run the website.

1. In Visual Studio, make sure you have webpack runner installed. We'll need this to generate script bundles. First run the webpack taskrunner to generate the script bundles.
2. Rather than using visual studio to run the app, it's recommended to setup an IIS website. Point it to the [app folder](https://github.com/mobsoftware/mobsocial/tree/development/Presentation/mobSocial.WebApp) e.g. **http://yourdomain.localhost.com**
3. Create a virtual directory called **api**  in this website and set it up as WebApplication. This should point to [Api](https://github.com/mobsoftware/mobsocial/tree/development/Presentation/mobSocial.WebApi). So the api endpoint becomes
**http://yourdomain.localhost.com/api**
4. Send a post request to **http://yourdomain.localhost.com/api** with parameters as mentioned [here](https://github.com/mobsoftware/mobsocial/issues/17#issuecomment-255956093)
5. Once you get the install success response, visit **http://yourdomain.localhost.com/**. You should be redirected to login page. Login with the details you provided in step 4.
6. You can visit **http://yourdomain.localhost.com/admin** to configure your application.

Let me know if you face any trouble with the above steps.

**Comment by CS-begginer** [comment]
@wittyansh 
Thanks. 
But How i can check WebPack Runner!!!!
Im learning ASP from 2 Week ago.
speak to me like a kid :D

**Comment by eretontali** [comment]
Hi, I'm still having problems to run :( 

![errorinitjs](https://cloud.githubusercontent.com/assets/7683891/20040106/ea7fa9bc-a416-11e6-98ef-5c37a1563644.JPG)

In Google Chrome:

![errorinchrome](https://cloud.githubusercontent.com/assets/7683891/20040110/fcbf2184-a416-11e6-8d5d-3145722eae53.JPG)

In Microsoft Edge:

![errorinedge](https://cloud.githubusercontent.com/assets/7683891/20040112/07afb4fa-a417-11e6-8abe-9643ada942f3.JPG)

**Comment by ins4n333** [comment]
Hi!
My HTTP POST request to /api/install was interrupted with error:
{
	"message": "An error has occurred.",
	"exceptionMessage": "Multiple actions were found that match the request: \r\nResponse on type mobSocial.WebApi.Controllers.InstallController\r\nRespondSuccess on type mobSocial.WebApi.Controllers.InstallController\r\nRespondSuccess on type mobSocial.WebApi.Controllers.InstallController\r\nRespondFailure on type mobSocial.WebApi.Controllers.InstallController\r\nRespondFailure on type mobSocial.WebApi.Controllers.InstallController",
	"exceptionType": "System.InvalidOperationException",
	"stackTrace": "   at System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.SelectAction(HttpControllerContext controllerContext)\r\n   at System.Web.Http.ApiController.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}

Can you help me?

**Comment by wittyansh** [comment]
Hi @ins4n333 The error occurs because of presence of similar routes and actions in old UI project. It has been removed now. You can safely delete the UI project and try again and this should fix this issue.

**Comment by ins4n333** [comment]
Hi @wittyansh. It's still not working. The error is the same. What am i doing wrong? I cloned this solution. Then I ran the web.api project in debug mode from visual studio (I test on vs 2013 and vs 2015). I sent request from fiddler... Beside that I installed web.api as IIS application,  but anyway received the error..

**Comment by wittyansh** [comment]
Can you please delete the UI folder, re-save Global.asax and try again. May be ASP.NET is still referring to the UI project files?

**Comment by ins4n333** [comment]
I tested on the lastest version (by this time was removed from solution and Presentation dir). I should add that I tried to install it on two different computers (Windows 10). The problem was the same

**Comment by fairmaker** [comment]
It would be very useful to have an installation video. Is much better than the boring and sometimes incomplete documentation, and save you time as well

**Comment by wittyansh** [comment]
Hi guys, Please see detailed how to install instructions [here](https://github.com/mobsoftware/mobsocial/wiki/How-to-install-mobSocial%3F)
